### ISSUE TITLE
Setting smoothing to "none" isn't respected in some cases when scaled

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/starling#17]
In renderCustom() in QuadBatch.hx, the following lines overwrite your own image smoothing preferences with a different value:

```
context.setSamplerStateAt(0, Context3DWrapMode.CLAMP, Context3DTextureFilter.NEAREST, Context3DMipFilter.MIPNONE);
```

I think it's in a few other places as well. As a result, the following code will show a smoothed image when scaled, even though it shouldn't:

```
var backbuffer:RenderTexture = new RenderTexture(384, 240, false);
var screen:Image = new Image(backbuffer);
screen.scale = 2;
screen.smoothing = "none";
addChild(screen);
```

**Comment by jgranick** [comment]
This should be fixed in my latest pass on comparing the original AS3 to the current Haxe port. Let me know if you experience other issues, thank you :smile:

**Comment by TerryCavanagh** [comment]
Hey hey! So I checked out the most recent version, and this seems to fix things for flash, woo! However, I'm still getting the problem on HTML5 and C++ :(

**Comment by jgranick** [comment]
Do you think it would be possible to whip up a small sample that I could use to replicate the issue?

**Comment by TerryCavanagh** [comment]
Yep! I'll do that and post again later!

**Comment by TerryCavanagh** [comment]
Ok, here's the example!

[smoothingtest.zip](https://github.com/openfl/starling/files/500434/smoothingtest.zip)

This program attaches a single 16x16 chessboard image to the stage, scaling it up by 20 with smoothing set to "none". It's using the current 1.8 branch of Starling locally in the source directory.

On my machine, on flash I get this:

![flash](https://cloud.githubusercontent.com/assets/2874150/18950918/3d9d3cfe-863a-11e6-8a63-dd4368e563b5.png)

In HTML5:

![html5](https://cloud.githubusercontent.com/assets/2874150/18950921/42d41e40-863a-11e6-8f0f-46f4fa30f9bd.png)

And with a native Windows build:

![windows](https://cloud.githubusercontent.com/assets/2874150/18950928/4acc4974-863a-11e6-86e9-a2dfa8c602ca.png)

For convience, here's the complete Game.hx file where the image is attached:

``` haxe
import starling.events.*;
import starling.display.*;
import starling.textures.*;
import starling.core.*;
import starling.utils.*;
import openfl.Assets;
import haxe.Timer;

class Game extends Sprite {
	public var starlingassets:AssetManager;
	
	public function new() {
		super();	
		addEventListener(Event.ADDED_TO_STAGE, onAdded);
	}
	
	public function onAdded(e:Event) {
		//Load assets
		starlingassets = new AssetManager();
		
		#if 0
		starlingassets.enqueue([
			"assets/chessboard.png",
		]);
		#else
		Timer.delay(function()
		{
				var tex:Texture = Texture.fromBitmapData(
						Assets.getBitmapData("assets/chessboard.png"), false);
				starlingassets.addTexture("chessboard", tex);
				
				init();
		}, 0);
		#end
		
		#if 0
		starlingassets.loadQueue(function(ratio:Float) {
			if (ratio == 1){
				init();
			}
		});
		#end
	}
	
	public function init() {
		var chessboard:Image = new Image(starlingassets.getTexture("chessboard"));
		chessboard.scale = 30;
		chessboard.smoothing = "none";
		addChild(chessboard);
	}
}
```

**Comment by TerryCavanagh** [comment]
(Also worth nothing: HTML5 builds usually scale their canvas to fit in a browser window, and native windows builds these days use a system DPI setting which scales up programs. (in my case, from 480 -> 600). Disabling DPI scaling on my exe didn't make a different in windows 10, and resizing my browser window didn't make a difference HTML5.)

**Comment by jgranick** [comment]
Thank you! Fixed in Context3D :smile:

**Comment by TerryCavanagh** [comment]
Awesome :D
